// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfzordJ6hmFnrBiBiEWwEBUZ1RWmImpQ',
    appId: '1:204038877618:web:d79872b1f80a234879b4ab',
    messagingSenderId: '204038877618',
    projectId: 'where-to-go-today-89dc3',
    authDomain: 'where-to-go-today-89dc3.firebaseapp.com',
    storageBucket: 'where-to-go-today-89dc3.appspot.com',
    measurementId: 'G-E2F41PSDHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN54CzlL6rDPR2z0i_s7nrYUzFaRWYSAQ',
    appId: '1:204038877618:android:61c121f7d7ae7b1779b4ab',
    messagingSenderId: '204038877618',
    projectId: 'where-to-go-today-89dc3',
    storageBucket: 'where-to-go-today-89dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1ClAyq6ngBPohG0G0F_P_6JZ0_WzTDI',
    appId: '1:204038877618:ios:a52402bb8a45edff79b4ab',
    messagingSenderId: '204038877618',
    projectId: 'where-to-go-today-89dc3',
    storageBucket: 'where-to-go-today-89dc3.appspot.com',
    iosClientId: '204038877618-ebefit4n6u2i4ub6li3768801adkeh2f.apps.googleusercontent.com',
    iosBundleId: 'ru.boostgrade.wtgt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1ClAyq6ngBPohG0G0F_P_6JZ0_WzTDI',
    appId: '1:204038877618:ios:a52402bb8a45edff79b4ab',
    messagingSenderId: '204038877618',
    projectId: 'where-to-go-today-89dc3',
    storageBucket: 'where-to-go-today-89dc3.appspot.com',
    iosClientId: '204038877618-ebefit4n6u2i4ub6li3768801adkeh2f.apps.googleusercontent.com',
    iosBundleId: 'ru.boostgrade.wtgt',
  );
}
